name: surfdock
channels:
  - conda-forge
  - nvidia
  - pytorch
  - pyg
dependencies:
  # core
  - python=3.10
  - pip

  # CUDA PyTorch stack
  - pytorch=2.2.*=*cuda12*
  - torchvision=0.17.*=*cuda12*
  - torchaudio=2.2.*=*cuda12*

  # PyG CUDA wheels (scatter/sparse/cluster pulled automatically)
  - pyg-lib

  # OpenMM & force-field tools (from README)
  - openmm=8.1.1
  - openmmforcefields=0.12.0
  - pdbfixer=1.9

  # full OpenFF toolkit
  - openff-toolkit=0.15.2
  - openff-interchange
  - openff-forcefields
  - openff-units=0.2.2
  - openff-utilities=0.1.12
  - openff-models
  - smirnoff99frosst

  # molecule / surface plumbing
  - openbabel=3.1.1
  - rdkit
  - mdanalysis
  - loguru
  - prefetch-generator
  - biopython=1.79

  # numerics / helpers
  - numpy
  - scipy
  - pandas
  - tqdm

  # remaining pip-only packages
  - pip:
      - fair-esm          # protein embeddings
      - spyrmsd
      - scikit-learn==1.3.2
      - accelerate==0.15.0
      - e3nn==0.5.1
      - huggingface-hub==0.17.3
      - torch-ema==0.3
      - torchmetrics==1.2.1
      - tokenizers==0.13.3
      - transformers==4.29.2
      - wandb==0.16.1
      - posebusters==0.2.7
      - dimorphite_dl
      # PyMesh 0.3.1 pre-built wheel
      - https://github.com/nuvolos-cloud/PyMesh/releases/download/v0.3.1/pymesh2-0.3.1-cp310-cp310-linux_x86_64.whl
