# only three changes, everything else stays exactly as in the README
name: surfdock
channels:
  - pytorch            # ① add PyTorch’s own channel
  - conda-forge
dependencies:
  - python=3.10
  # ② loosen PyTorch-stack pins → let the solver pick a compatible trio
  - pytorch
  - torchvision
  - torchaudio
  # ③ drop any hard-pinned pyg-lib / pyg-torch; keep it flexible
  - pyg-lib
  - numpy
  - scipy
  - rdkit
  - pip
  - pip:
      # we will install SurfDock from its Git tag inside the Dockerfile
      - "git+https://github.com/CAODH/SurfDock.git@beta_v_0.03"
